server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: service

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:h2:mem:university-service;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: username
    password: password
    driverClassName: org.h2.Driver
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: none
      open-in-view: true
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: false
    h2:
      console:
        enabled: true


springdoc:
  swagger-ui:
    path:
      /demo-service/swagger-ui.html
